"""Various template utilities that are injected as context into templates."""

from typing import TYPE_CHECKING

from hadalized.theme import Style, T

if TYPE_CHECKING:
    from collections.abc import Iterator

    from hadalized.theme import Theme


HL_GROUP_FIELDS: set[str] = set(Style.model_fields.keys()) - {"link"}


def default_mapping() -> dict[str, T]:
    """Default mapping of neovim highlight groups to theme fields.

    Returns:
        A dict of neovim highlight group name to Theme field.

    """
    return {
        "@attribute": T.attribute,
        "@attribute.builtin": T.attribute_builtin,
        "@boolean": T.boolean,
        "@character": T.character,
        "@character.special": T.character_special,
        "@comment": T.comment,
        "@comment.documentation": T.comment_documentation,
        "@comment.error": T.comment_error,
        "@comment.note": T.comment_note,
        "@comment.todo": T.comment_todo,
        "@comment.warning": T.comment_warning,
        "@constant": T.constant,
        "@constant.builtin": T.constant_builtin,
        "@constant.macro": T.constant_macro,
        "@constructor": T.constructor,
        "@diff.delta": T.diff_delta,
        "@diff.minus": T.diff_minus,
        "@diff.plus": T.diff_plus,
        "@function": T.function,
        "@function.builtin": T.function_builtin,
        "@function.call": T.function_call,
        "@function.macro": T.function_macro,
        "@function.method": T.function_method,
        "@function.method.call": T.function_method_call,
        "@keyword": T.keyword,
        "@keyword.conditional": T.keyword_conditional,
        "@keyword.conditional.ternary": T.keyword_conditional_ternary,
        "@keyword.coroutine": T.keyword_coroutine,
        "@keyword.debug": T.keyword_debug,
        "@keyword.directive": T.keyword_directive,
        "@keyword.directive.define": T.keyword_directive_define,
        "@keyword.exception": T.keyword_exception,
        "@keyword.function": T.keyword_function,
        "@keyword.import": T.keyword_import,
        "@keyword.modifier": T.keyword_modifier,
        "@keyword.operator": T.keyword_operator,
        "@keyword.repeat": T.keyword_repeat,
        "@keyword.return": T.keyword_return,
        "@keyword.type": T.keyword_type,
        "@label": T.label,
        "@lsp.mod.abstract": T.abstract,
        "@lsp.mod.async": T.function_async,
        "@lsp.mod.declaration": T.declaration,
        "@lsp.mod.defaultLibrary": T.module_builtin,
        "@lsp.mod.definition": T.type_definition,
        "@lsp.mod.deprecated": T.diagnostic_deprecated,
        "@lsp.mod.documentation": T.string_documentation,
        "@lsp.mod.modification": T.variable_modification,
        "@lsp.mod.readonly": T.constant,
        "@lsp.mod.static": T.static_member,
        "@lsp.type.class": T.class_type,
        "@lsp.type.comment": T.comment,
        "@lsp.type.decorator": T.attribute,
        "@lsp.type.enum": T.enum,
        "@lsp.type.enumMember": T.enum_member,
        "@lsp.type.event": T.event_property,
        "@lsp.type.function": T.function,
        "@lsp.type.interface": T.interface,
        "@lsp.type.keyword": T.keyword,
        "@lsp.type.macro": T.function_macro,
        "@lsp.type.method": T.function_method,
        "@lsp.type.modifier": T.keyword_modifier,
        "@lsp.type.namespace": T.module,
        "@lsp.type.number": T.number,
        "@lsp.type.operator": T.operator,
        "@lsp.type.parameter": T.variable_parameter,
        "@lsp.type.property": T.property,
        "@lsp.type.regexp": T.string_regexp,
        "@lsp.type.string": T.string,
        "@lsp.type.struct": T.struct,
        "@lsp.type.type": T.type,
        "@lsp.type.typeParameter": T.type_parameter,
        "@lsp.type.variable": T.variable,
        "@markup.heading": T.markup_heading,
        "@markup.heading.1": T.markup_heading_1,
        "@markup.heading.2": T.markup_heading_2,
        "@markup.heading.3": T.markup_heading_3,
        "@markup.heading.4": T.markup_heading_4,
        "@markup.heading.5": T.markup_heading_5,
        "@markup.heading.6": T.markup_heading_6,
        "@markup.italic": T.markup_italic,
        "@markup.link": T.markup_link,
        "@markup.link.label": T.markup_link_label,
        "@markup.link.url": T.markup_link_url,
        "@markup.list": T.markup_list,
        "@markup.list.checked": T.markup_list_checked,
        "@markup.list.unchecked": T.markup_list_unchecked,
        "@markup.math": T.markup_math,
        "@markup.quote": T.markup_quote,
        "@markup.raw": T.markup_raw,
        "@markup.raw.block": T.markup_raw_block,
        "@markup.strikethrough": T.markup_strikethrough,
        "@markup.strong": T.markup_strong,
        "@markup.underline": T.markup_underline,
        "@module": T.module,
        "@module.builtin": T.module_builtin,
        "@number": T.number,
        "@number.float": T.number_float,
        "@operator": T.operator,
        "@property": T.property,
        "@punctuation.bracket": T.punctuation_bracket,
        "@punctuation.delimiter": T.punctuation_delimiter,
        "@punctuation.special": T.punctuation_special,
        "@string": T.string,
        "@string.documentation": T.string_documentation,
        "@string.escape": T.string_escape,
        "@string.regexp": T.string_regexp,
        "@string.special": T.string_special,
        "@string.special.path": T.string_special_path,
        "@string.special.symbol": T.string_special_symbol,
        "@string.special.url": T.string_special_url,
        "@tag": T.tag,
        "@tag.attribute": T.tag_attribute,
        "@tag.builtin": T.tag_builtin,
        "@tag.delimiter": T.tag_delimiter,
        "@type": T.type,
        "@type.builtin": T.type_builtin,
        "@type.definition": T.type_definition,
        "@variable": T.variable,
        "@variable.builtin": T.variable_builtin,
        "@variable.member": T.variable_member,
        "@variable.parameter": T.variable_parameter,
        "@variable.parameter.builtin": T.variable_parameter_builtin,
        "ColorColumn": T.color_column,
        "ComplMatchIns": T.completion_match_insert,
        "Conceal": T.conceal,
        "CurSearch": T.search_current_match,
        "Cursor": T.cursor,
        "CursorColumn": T.cursor_column,
        "CursorIM": T.cursor,
        "CursorLine": T.cursor_line,
        "CursorLineFold": T.cursor_line_fold,
        "CursorLineNr": T.cursor_line_number,
        "CursorLineSign": T.cursor_line_gutter,
        "DiagnosticDeprecated": T.diagnostic_deprecated,
        "DiagnosticError": T.diagnostic_error,
        "DiagnosticFloatingError": T.diagnostic_floating_error,
        "DiagnosticFloatingHint": T.diagnostic_floating_hint,
        "DiagnosticFloatingInfo": T.diagnostic_floating_info,
        "DiagnosticFloatingOk": T.diagnostic_floating_ok,
        "DiagnosticFloatingWarn": T.diagnostic_floating_warn,
        "DiagnosticHint": T.diagnostic_hint,
        "DiagnosticInfo": T.diagnostic_info,
        "DiagnosticOk": T.diagnostic_ok,
        "DiagnosticSignError": T.diagnostic_sign_error,
        "DiagnosticSignHint": T.diagnostic_sign_hint,
        "DiagnosticSignInfo": T.diagnostic_sign_info,
        "DiagnosticSignOk": T.diagnostic_sign_ok,
        "DiagnosticSignWarn": T.diagnostic_sign_warn,
        "DiagnosticUnderlineError": T.diagnostic_underline_error,
        "DiagnosticUnderlineHint": T.diagnostic_underline_hint,
        "DiagnosticUnderlineInfo": T.diagnostic_underline_info,
        "DiagnosticUnderlineOk": T.diagnostic_underline_ok,
        "DiagnosticUnderlineWarn": T.diagnostic_underline_warn,
        "DiagnosticUnnecessary": T.diagnostic_unnecessary,
        "DiagnosticVirtualLinesError": T.diagnostic_virtual_lines_error,
        "DiagnosticVirtualLinesHint": T.diagnostic_virtual_lines_hint,
        "DiagnosticVirtualLinesInfo": T.diagnostic_virtual_lines_info,
        "DiagnosticVirtualLinesOk": T.diagnostic_virtual_lines_ok,
        "DiagnosticVirtualLinesWarn": T.diagnostic_virtual_lines_warn,
        "DiagnosticVirtualTextError": T.diagnostic_virtual_text_error,
        "DiagnosticVirtualTextHint": T.diagnostic_virtual_text_hint,
        "DiagnosticVirtualTextInfo": T.diagnostic_virtual_text_info,
        "DiagnosticVirtualTextOk": T.diagnostic_virtual_text_ok,
        "DiagnosticVirtualTextWarn": T.diagnostic_virtual_text_warn,
        "DiagnosticWarn": T.diagnostic_warn,
        "DiffAdd": T.diff_plus,
        "DiffChange": T.diff_delta,
        "DiffDelete": T.diff_minus,
        "DiffText": T.diff_delta,
        "Directory": T.string_special_path,
        "EndOfBuffer": T.end_of_buffer,
        "ErrorMsg": T.message_error,
        "FloatBorder": T.floating_window_border,
        "FloatFooter": T.floating_window_footer,
        "FloatTitle": T.floating_window_title,
        "FoldColumn": T.fold_column,
        "Folded": T.folded_line,
        "IncSearch": T.search_incremental,
        "LineNr": T.line_number,
        "LineNrAbove": T.line_number_above,
        "LineNrBelow": T.line_number_below,
        "LspCodeLens": T.lsp_code_lens,
        "LspCodeLensSeparator": T.lsp_code_lens,
        "LspInlayHint": T.lsp_inlay_hint,
        "LspReferenceRead": T.lsp_reference_read,
        "LspReferenceTarget": T.lsp_reference_target,
        "LspReferenceText": T.lsp_reference_text,
        "LspReferenceWrite": T.lsp_reference_write,
        "LspSignatureActiveParameter": T.lsp_signature_active_parameter,
        "MatchParen": T.matched_bracket,
        "Menu": T.menu,
        "ModeMsg": T.message_mode,
        "MoreMsg": T.message_more,
        "MsgArea": T.message,
        "MsgSeparator": T.message_separator,
        "NonText": T.non_text,
        "Normal": T.main,
        "NormalFloat": T.floating_window,
        "NormalNC": T.main_unfocused,
        "Pmenu": T.floating_window,
        "PmenuSel": T.selection,
        "Question": T.message_question,
        "QuickFixLine": T.selection,
        "ScrollBar": T.scrollbar,
        "Search": T.search,
        "SignColumn": T.gutter,
        "SpecialKey": T.special_key,
        "SpellBad": T.spell_bad,
        "SpellCap": T.spell_cap,
        "SpellLocal": T.spell_local,
        "SpellRare": T.spell_rare,
        "StatusLine": T.status_line,
        "StatusLineNC": T.status_line_unfocused,
        "Substitute": T.search_replace,
        "TabLine": T.tab_line,
        "TabLineFill": T.tab_line_fill,
        "TabLineSel": T.tab_line_sel,
        "TermCursor": T.terminal_cursor,
        "Title": T.markup_heading,
        "Tooltip": T.tooltip,
        "Visual": T.selection,
        "VisualNOS": T.selection,
        "WarningMsg": T.message_warn,
        "Whitespace": T.whitespace,
        "WildMenu": T.search_current_match,
        "WinSeparator": T.window_separator,
        "lCursor": T.cursor,
        # "PmenuExtra": xxx,
        # "PmenuExtraSel": xxx,
        # "PmenuKind": xxx,
        # "PmenuKindSel": xxx,
        # "PmenuMatchSel": xxx,
        # "PmenuPatch": xxx,
        # "PmenuSbar": xxx,
        # "PmenuThumb": xxx,
        # "SnippetTabstop": xxx,
        # "WinBar": xxx,
        # "WinBarNC": xxx,
    }


def transform(
    theme: Theme,
    mapping: dict[str, T] | None = None,
) -> Iterator[tuple[str, str]]:
    """Convert each theme style to a neovim highlight input.

    Yields:
        A pair consisting of a neovim highlight group name and lua
        highlight group data structure (as string).

    """
    mapping = mapping or default_mapping()
    for group, style in theme.remap(mapping):
        settings = style.model_dump_lua(
            exclude_unset=True,
            include=HL_GROUP_FIELDS,
            indent=None,
        )
        yield group, settings
