"""Various template utilities that are injected as context into templates."""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterator

    from hadalized.style import Style
    from hadalized.theme import Theme


HL_GROP_FIELD_EXCLUDE = {"link", "exclude", "shadow", "border"}


def mapping(theme: Theme) -> dict[str, Style]:
    """Default mapping of neovim highlight groups to theme fields.

    Returns:
        A dict of neovim highlight group name to Theme field.

    """
    return {
        "@attribute": theme.attribute,
        "@attribute.builtin": theme.attribute_builtin,
        "@boolean": theme.boolean,
        "@character": theme.character,
        "@character.special": theme.character_special,
        "@comment": theme.comment,
        "@comment.documentation": theme.comment_documentation,
        "@comment.error": theme.comment_error,
        "@comment.note": theme.comment_note,
        "@comment.todo": theme.comment_todo,
        "@comment.warning": theme.comment_warning,
        "@constant": theme.constant,
        "@constant.builtin": theme.constant_builtin,
        "@constant.macro": theme.constant_macro,
        "@constructor": theme.constructor,
        "@diff.delta": theme.diff_delta,
        "@diff.minus": theme.diff_minus,
        "@diff.plus": theme.diff_plus,
        "@function": theme.function,
        "@function.builtin": theme.function_builtin,
        "@function.call": theme.function_call,
        "@function.macro": theme.function_macro,
        "@function.method": theme.function_method,
        "@function.method.call": theme.function_method_call,
        "@keyword": theme.keyword,
        "@keyword.conditional": theme.keyword_conditional,
        "@keyword.conditional.ternary": theme.keyword_conditional_ternary,
        "@keyword.coroutine": theme.keyword_coroutine,
        "@keyword.debug": theme.keyword_debug,
        "@keyword.directive": theme.keyword_directive,
        "@keyword.directive.define": theme.keyword_directive_define,
        "@keyword.exception": theme.keyword_exception,
        "@keyword.function": theme.keyword_function,
        "@keyword.import": theme.keyword_import,
        "@keyword.modifier": theme.keyword_modifier,
        "@keyword.operator": theme.keyword_operator,
        "@keyword.repeat": theme.keyword_repeat,
        "@keyword.return": theme.keyword_return,
        "@keyword.type": theme.keyword_type,
        "@label": theme.label,
        "@lsp.mod.abstract": theme.abstract,
        "@lsp.mod.async": theme.function_async,
        "@lsp.mod.declaration": theme.declaration,
        "@lsp.mod.defaultLibrary": theme.module_builtin,
        "@lsp.mod.definition": theme.type_definition,
        "@lsp.mod.deprecated": theme.diagnostic_deprecated,
        "@lsp.mod.documentation": theme.string_documentation,
        "@lsp.mod.modification": theme.variable_modification,
        "@lsp.mod.readonly": theme.constant,
        "@lsp.mod.static": theme.static_member,
        "@lsp.type.class": theme.classes,
        "@lsp.type.comment": theme.comment,
        "@lsp.type.decorator": theme.attribute,
        "@lsp.type.enum": theme.enum,
        "@lsp.type.enumMember": theme.enum_member,
        "@lsp.type.event": theme.event_property,
        "@lsp.type.function": theme.function,
        "@lsp.type.interface": theme.interface,
        "@lsp.type.keyword": theme.keyword,
        "@lsp.type.macro": theme.function_macro,
        "@lsp.type.method": theme.function_method,
        "@lsp.type.modifier": theme.keyword_modifier,
        "@lsp.type.namespace": theme.module,
        "@lsp.type.number": theme.number,
        "@lsp.type.operator": theme.operator,
        "@lsp.type.parameter": theme.variable_parameter,
        "@lsp.type.property": theme.prop,
        "@lsp.type.regexp": theme.string_regexp,
        "@lsp.type.string": theme.string,
        "@lsp.type.struct": theme.struct,
        "@lsp.type.type": theme.type,
        "@lsp.type.typeParameter": theme.type_parameter,
        "@lsp.type.variable": theme.variable,
        "@markup.heading": theme.markup_heading,
        "@markup.heading.1": theme.markup_heading_1,
        "@markup.heading.2": theme.markup_heading_2,
        "@markup.heading.3": theme.markup_heading_3,
        "@markup.heading.4": theme.markup_heading_4,
        "@markup.heading.5": theme.markup_heading_5,
        "@markup.heading.6": theme.markup_heading_6,
        "@markup.italic": theme.markup_italic,
        "@markup.link": theme.markup_link,
        "@markup.link.label": theme.markup_link_label,
        "@markup.link.url": theme.markup_link_url,
        "@markup.list": theme.markup_list,
        "@markup.list.checked": theme.markup_list_checked,
        "@markup.list.unchecked": theme.markup_list_unchecked,
        "@markup.math": theme.markup_math,
        "@markup.quote": theme.markup_quote,
        "@markup.raw": theme.markup_raw,
        "@markup.raw.block": theme.markup_raw_block,
        "@markup.strikethrough": theme.markup_strikethrough,
        "@markup.strong": theme.markup_strong,
        "@markup.underline": theme.markup_underline,
        "@module": theme.module,
        "@module.builtin": theme.module_builtin,
        "@number": theme.number,
        "@number.float": theme.number_float,
        "@operator": theme.operator,
        "@property": theme.prop,
        "@punctuation.bracket": theme.punctuation_bracket,
        "@punctuation.delimiter": theme.punctuation_delimiter,
        "@punctuation.special": theme.punctuation_special,
        "@string": theme.string,
        "@string.documentation": theme.string_documentation,
        "@string.escape": theme.string_escape,
        "@string.regexp": theme.string_regexp,
        "@string.special": theme.string_special,
        "@string.special.path": theme.string_special_path,
        "@string.special.symbol": theme.string_special_symbol,
        "@string.special.url": theme.string_special_url,
        "@tag": theme.tag,
        "@tag.attribute": theme.tag_attribute,
        "@tag.builtin": theme.tag_builtin,
        "@tag.delimiter": theme.tag_delimiter,
        "@type": theme.type,
        "@type.builtin": theme.type_builtin,
        "@type.definition": theme.type_definition,
        "@variable": theme.variable,
        "@variable.builtin": theme.variable_builtin,
        "@variable.member": theme.variable_member,
        "@variable.parameter": theme.variable_parameter,
        "@variable.parameter.builtin": theme.variable_parameter_builtin,
        "Added": theme.diff_plus,
        "Boolean": theme.boolean,
        "Changed": theme.diff_delta,
        "Character": theme.character,
        "ColorColumn": theme.color_column,
        "Comment": theme.comment,
        "ComplMatchIns": theme.completion_match_insert,
        "Conceal": theme.concealed,
        "Conditional": theme.keyword_conditional,
        "Constant": theme.constant,
        "CurSearch": theme.search_current_match,
        "Cursor": theme.cursor,
        "CursorColumn": theme.cursor_column,
        "CursorIM": theme.cursor,
        "CursorLine": theme.cursor_line,
        "CursorLineFold": theme.cursor_line_fold,
        "CursorLineNr": theme.cursor_line_number,
        "CursorLineSign": theme.cursor_line_gutter,
        "Debug": theme.keyword_debug,
        "Delimiter": theme.punctuation_delimiter,
        "DiagnosticDeprecated": theme.diagnostic_deprecated,
        "DiagnosticError": theme.diagnostic_error,
        "DiagnosticFloatingError": theme.diagnostic_floating_error,
        "DiagnosticFloatingHint": theme.diagnostic_floating_hint,
        "DiagnosticFloatingInfo": theme.diagnostic_floating_info,
        "DiagnosticFloatingOk": theme.diagnostic_floating_ok,
        "DiagnosticFloatingWarn": theme.diagnostic_floating_warn,
        "DiagnosticHint": theme.diagnostic_hint,
        "DiagnosticInfo": theme.diagnostic_info,
        "DiagnosticOk": theme.diagnostic_ok,
        "DiagnosticSignError": theme.diagnostic_gutter_error,
        "DiagnosticSignHint": theme.diagnostic_gutter_info,
        "DiagnosticSignInfo": theme.diagnostic_gutter_info,
        "DiagnosticSignOk": theme.diagnostic_gutter_ok,
        "DiagnosticSignWarn": theme.diagnostic_gutter_warn,
        "DiagnosticUnderlineError": theme.diagnostic_underline_error,
        "DiagnosticUnderlineHint": theme.diagnostic_underline_hint,
        "DiagnosticUnderlineInfo": theme.diagnostic_underline_info,
        "DiagnosticUnderlineOk": theme.diagnostic_underline_ok,
        "DiagnosticUnderlineWarn": theme.diagnostic_underline_warn,
        "DiagnosticUnnecessary": theme.diagnostic_unnecessary,
        "DiagnosticVirtualLinesError": theme.diagnostic_virtual_lines_error,
        "DiagnosticVirtualLinesHint": theme.diagnostic_virtual_lines_hint,
        "DiagnosticVirtualLinesInfo": theme.diagnostic_virtual_lines_info,
        "DiagnosticVirtualLinesOk": theme.diagnostic_virtual_lines_ok,
        "DiagnosticVirtualLinesWarn": theme.diagnostic_virtual_lines_warn,
        "DiagnosticVirtualTextError": theme.diagnostic_virtual_text_error,
        "DiagnosticVirtualTextHint": theme.diagnostic_virtual_text_hint,
        "DiagnosticVirtualTextInfo": theme.diagnostic_virtual_text_info,
        "DiagnosticVirtualTextOk": theme.diagnostic_virtual_text_ok,
        "DiagnosticVirtualTextWarn": theme.diagnostic_virtual_text_warn,
        "DiagnosticWarn": theme.diagnostic_warn,
        "DiffAdd": theme.diff_plus,
        "DiffChange": theme.diff_delta,
        "DiffDelete": theme.diff_minus,
        "DiffText": theme.diff_delta,
        "Directory": theme.string_special_path,
        "EndOfBuffer": theme.end_of_buffer,
        "Error": theme.diagnostic_error,
        "ErrorMsg": theme.message_error,
        "Exception": theme.keyword_exception,
        "Float": theme.number_float,
        "FloatBorder": theme.floating_window_border,
        "FloatFooter": theme.floating_window_footer,
        "FloatTitle": theme.floating_window_title,
        "FoldColumn": theme.fold_column,
        "Folded": theme.folded_line,
        "Function": theme.function,
        "Identifier": theme.variable,
        "Ignore": theme.concealed,
        "IncSearch": theme.search_incremental,
        "Include": theme.keyword_import,
        "Keyword": theme.keyword,
        "Label": theme.label,
        "LineNr": theme.line_number,
        "LineNrAbove": theme.line_number_above,
        "LineNrBelow": theme.line_number_below,
        "LspCodeLens": theme.lsp_code_lens,
        "LspCodeLensSeparator": theme.lsp_code_lens_separator,
        "LspInlayHint": theme.lsp_inlay_hint,
        "LspReferenceRead": theme.lsp_reference_read,
        "LspReferenceTarget": theme.lsp_reference_target,
        "LspReferenceText": theme.lsp_reference_text,
        "LspReferenceWrite": theme.lsp_reference_write,
        "LspSignatureActiveParameter": theme.lsp_signature_active_parameter,
        "Macro": theme.function_macro,
        "MatchParen": theme.matched_bracket,
        "Menu": theme.menu,
        "ModeMsg": theme.message_mode,
        "MoreMsg": theme.message_more,
        "MsgArea": theme.message,
        "MsgSeparator": theme.message_separator,
        "NonText": theme.non_text,
        "Normal": theme.main,
        "NormalFloat": theme.floating_window,
        "NormalNC": theme.unfocused,
        "Number": theme.number,
        "Operator": theme.operator,
        "Pmenu": theme.floating_window,
        "PmenuSel": theme.selection,
        "PreCondit": theme.keyword_conditional,
        "PreProc": theme.function_macro,
        "Question": theme.message_question,
        "QuickFixLine": theme.selection,
        "Removed": theme.diff_minus,
        "Repeat": theme.keyword_repeat,
        "ScrollBar": theme.scrollbar,
        "Search": theme.search,
        "SignColumn": theme.gutter,
        "SpecialChar": theme.string_special,
        "SpecialComment": theme.comment_special,
        "SpecialKey": theme.special_key,
        "SpellBad": theme.spellcheck_error,
        "SpellCap": theme.spellcheck_warn,
        "SpellLocal": theme.spellcheck_hint,
        "SpellRare": theme.spellcheck_info,
        "Statement": theme.main,
        "StatusLine": theme.status_line,
        "StatusLineNC": theme.status_line_unfocused,
        "StorageClass": theme.keyword_modifier,
        "String": theme.string,
        "Structure": theme.struct,
        "Substitute": theme.search_replace,
        "TabLine": theme.tab_line,
        "TabLineFill": theme.tab_line_fill,
        "TabLineSel": theme.tab_line_sel,
        "Tag": theme.tag,
        "TermCursor": theme.terminal_cursor,
        "Title": theme.markup_heading,
        "Todo": theme.comment_todo,
        "Tooltip": theme.tooltip,
        "Type": theme.type,
        "TypeDef": theme.type_definition,
        "Underlined": theme.markup_underline,
        "Visual": theme.selection,
        "VisualNOS": theme.selection,
        "WarningMsg": theme.message_warn,
        "Whitespace": theme.whitespace,
        "WildMenu": theme.search_current_match,
        "WinSeparator": theme.window_separator,
        "lCursor": theme.cursor,
        # "PmenuExtra": xxx,
        # "PmenuExtraSel": xxx,
        # "PmenuKind": xxx,
        # "PmenuKindSel": xxx,
        # "PmenuMatchSel": xxx,
        # "PmenuPatch": xxx,
        # "PmenuSbar": xxx,
        # "PmenuThumb": xxx,
        # "SnippetTabstop": xxx,
        # "WinBar": xxx,
        # "WinBarNC": xxx,
    }


def style_dump_lua(style: Style) -> str:
    """Convert a Style instance to a lua table.

    Returns:
        The style as a serialized lua table string.

    """
    return style.model_dump_lua(
        exclude_unset=True,
        exclude=HL_GROP_FIELD_EXCLUDE,
        indent=None,
    )


def transform(theme: Theme) -> Iterator[tuple[str, str]]:
    """Convert each theme style to a neovim highlight input.

    Yields:
        A pair consisting of a neovim highlight group name and lua
        highlight group data structure (as string).

    """
    for group, style in mapping(theme).items():
        settings = style.model_dump_lua(
            exclude_unset=True,
            exclude=HL_GROP_FIELD_EXCLUDE,
            indent=None,
        )
        yield group, settings
